// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2s61wlf4EYAalJXqODJsO7qv18-eTVqI',
    appId: '1:803585236818:android:9d9a365a4b94d98a2da48b',
    messagingSenderId: '803585236818',
    projectId: 'cafegourmet-b40f9',
    databaseURL: 'https://cafegourmet-b40f9-default-rtdb.firebaseio.com',
    storageBucket: 'cafegourmet-b40f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArCzPR6tv4qFFezHVb7YkVP9U1cxtIHZc',
    appId: '1:803585236818:ios:0b95f27d6acdc11c2da48b',
    messagingSenderId: '803585236818',
    projectId: 'cafegourmet-b40f9',
    databaseURL: 'https://cafegourmet-b40f9-default-rtdb.firebaseio.com',
    storageBucket: 'cafegourmet-b40f9.appspot.com',
    iosClientId: '803585236818-okroolp8l1djj18sol304b4v6q5kuqtl.apps.googleusercontent.com',
    iosBundleId: 'com.cafeGourmet',
  );
}
